### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pniedzielski** [genkimarshall/blog#1]
What is the license for these posts?  :smile:

**Comment by genkimarshall** [comment]
Hahaha I guess it's a free for all huh :P
(And this is a good reminder that I haven't updated my `laptop.md` post. Lol. Gonna get to that when a replacement arrives -- that one had too many issues, sadly.)

**Comment by genkimarshall** [comment]
Resolved as per 9cef898c50d7c3b101500b0207ea16ae69d06a30
:D
