### ISSUE TITLE
Error in Applying Discount Comes in Core of Magento

### ISSUE THREAD

**Issue by aishwaryacedcoss** [genkimarshall/blog#7]
I have created a coupon programmatically and when I have applied that coupon in discount it is giving the Error in core as:-
"Fatal error: Cannot use assign-op operators with overloaded objects nor string offsets in /opt/lampp/htdocs/workspace/magento_2_Aug/magento2/app/code/Magento/SalesRule/Model/Rule/Action/Discount/CartFixed.php on line 70"
            $cartRules[$rule->getId()] -= $baseDiscountAmount;

Solution:-When I have changed the code to :-
            $cartRules[$rule->getId()] = $cartRules[$rule->getId()]-$baseDiscountAmount;
It works.
                                                                                                                                 Thank you

**Comment by pniedzielski** [comment]
Hi, did you mean to post this issue to the a [magneto repository](https://github.com/magento/magento2)?

**Comment by aishwaryacedcoss** [comment]
O yeah I have to post there....
